
IMO/LR/IHS No.: ImoNumber
Name of Ship: ShipName
MMSI: MMSI
Displacement: Displacement 
Breadth Extreme: BreadthExtreme
Breadth Moulded:  BreadthMoulded
Length BP: LengthBP
Length Registered: LengthRegistered
Total KW Main Eng: TotalKWMainEng