
from . import *
from . import Base
class MergedTableResambled(Base):
    __tablename__ = "mergedtableresambled"
    MergedTableResambledID = Column(Integer, primary_key=True, autoincrement=True)
    PositionReportID = Column(Integer, ForeignKey('positionreport.PositionReportID'), index=True)
    ShipStaticDataID = Column(Integer, ForeignKey('shipstaticdata.ShipStaticDataID'), index=True)
    ShipCommonDataID = Column(UUID(as_uuid=True), ForeignKey('shipcommondata.ShipCommonDataID'), index=True)
    MMSI = Column(Integer)
    MessageType = Column(String(255))
    ShipName = Column(String(255))
    TimeUtc = Column(DateTime)
    SubscribeMessageID = Column(UUID(as_uuid=True),ForeignKey('subscribemessage.SubscribeMessageID'))
    MessageID = Column(Integer)
    RepeatIndicator = Column(Integer)
    Valid = Column(Boolean)
    Geom = Column(Geometry(geometry_type='POINT', srid=4326, spatial_index=True, use_typmod=True))
    Cog = Column(Float)
    CommunicationState = Column(Integer)
    NavigationalStatus = Column(Integer)
    PositionAccuracy = Column(Boolean)
    Raim = Column(Boolean)
    RateOfTurn = Column(Integer)
    Sog = Column(Float)
    Spare = Column(Integer)
    SpecialManoeuvreIndicator = Column(Integer)
    Timestamp = Column(Integer)
    TrueHeading = Column(Integer)
    AisVersion = Column(Integer)
    CallSign = Column(String(10))
    Destination = Column(String(255))
    DimensionA = Column(Integer)
    DimensionB = Column(Integer)
    DimensionC = Column(Integer)
    DimensionD = Column(Integer)
    Dte = Column(Boolean)
    EtaDay = Column(Integer)
    EtaHour = Column(Integer)
    EtaMinute = Column(Integer)
    EtaMonth = Column(Integer)
    FixType = Column(Integer)
    ImoNumber = Column(Integer)
    MaximumStaticDraught = Column(Float)
    Name = Column(String(255))
    ShipType = Column(Integer)

    idx_mergedtableresambled_geom = Index('idx_mergedtableresambled_geom', Geom,postgresql_using='gist')
    idx_mergedtableresambled_mmsi = Index('idx_mergedtableresambled_mmsi', MMSI)
    idx_mergedtableresambled_time_utc = Index('idx_mergedtableresambled_time_utc', TimeUtc)
    idx_mergedtableresambled_ship_type = Index('idx_mergedtableresambled_ship_type', ShipType)
    idx_mergedtableresambled_ShipCommonDataID = Index('idx_mergedtableresambled_ShipCommonDataID', ShipCommonDataID)
    idx_mergedtableresambled_imo_number = Index('idx_mergedtableresambled_imo_number', ImoNumber)
    idx_mergedtableresambled_positionreportid = Index('idx_mergedtableresambled_positionreportid', PositionReportID)
    idx_mergedtableresambled_shipstaticdataid = Index('idx_mergedtableresambled_shipstaticdataid', ShipStaticDataID)
    idx_mergedtableresambled_subscribemessageid = Index('idx_mergedtableresambled_subscribemessageid', SubscribeMessageID)
    idx_mergedtableresambled_shipname = Index('idx_mergedtableresambled_shipname', ShipName)
